version: '3.8'

services:
  secpro:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - FLASK_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb+srv://secpro_user:${MONGO_PASSWORD}@secpro.vexiur2.mongodb.net/?retryWrites=true&w=majority&appName=secpro
      - MONGO_DB_NAME=${MONGO_DB_NAME:-secpro}
      - REDIS_URL=redis://default:PIa5xxSO9Ue8kkoTaV4jU4uIvzhuTcM0@redis-14228.c305.ap-south-1-1.ec2.redns.redis-cloud.com:14228
      - REDIS_PREFIX=${REDIS_PREFIX:-secpro}
      - SECRET_KEY=${SECRET_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG_MODE=False
      - ENABLE_AUTH=true
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-30}
      - MAX_CONCURRENT_SCANS=${MAX_CONCURRENT_SCANS:-5}
      - SCAN_TIMEOUT=${SCAN_TIMEOUT:-300}
    volumes:
      - ./logs:/app/logs:rw
      - ./results:/app/results:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
